### PR TITLE
do not define `Seq` at all on OCaml >= 4.07

### LINKED ISSUE #12: Library should be empty for >= 4.07?
Currently the `seq` library re-exports `Stdlib.Seq` for versions of OCaml >= 4.07. This causes problems when using `(implicit_transitive_deps false)` in Dune (see eg https://github.com/ocaml/merlin/issues/1500).

Wouldn't it be better to simply define an _empty_ library for 4.07 and later, so that clients of this library would directly depend on `Stdlib.Seq` which would avoid the above problem?

### PR DESCRIPTION
**Pull request by c-cube**
close #12 I think.

@nojb what do you think?

### CODE REVIEW

**Comment by nojb** [comment]
This looks good to me, thanks @c-cube! I'm also pinging @dra27 anyway as an expert in all things OPAM to double check that I'm not missing anything.

**Comment by dra27** [comment]
This looks good to me, too. In fact, I like the trick for getting an empty module (I'd tried all sorts of other ideas in stdlib-shims and camlp-streams, but generating the module like that didn't occur to me!)

There is one (small) downside - OCaml 4.07-4.10 doesn't support empty libraries for MSVC. In camlp-streams, I chose to live with that for the time being.

**Review by nojb — APPROVED** [review]
Given @dra27's assent I'm giving this PR a formal approval. Thanks @c-cube for the speedy patch!

**Comment by c-cube** [comment]
Thank you for reviewing, my opam-fu is pretty basic :)

**Pull request merged**
